pipeline {
  agent {
        label 'slave1'
    }
  stages {
        stage("ADD docker") {
            steps {
                sh '''
                if 
                docker -v
                then 
                echo 'docker installed'
                else
                sudo apt-get update
                sudo apt-get install \
                ca-certificates \
                curl \
                gnupg \
                lsb-release
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
                echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
                sudo apt-get update && sudo apt-get install docker-ce docker-ce-cli containerd.io -y
                sudo usermod -aG docker vagrant
                fi
                '''
            }
        }
        stage("Checkout Git") {
            steps {
                git branch: 'bh-devops-01-22', url: 'https://github.com/vbrilik/belhard-devops.git' 
            }
        }
        stage("Build and run conteiner") {
            steps {
                sh '''
                docker build ./Viktor_Brilevich/12.Jenkins/part2/ -t homework:speedtest
                mkdir -p ./Viktor_Brilevich/12.Jenkins/part2/log
                if docker ps 
		then
		docker stop $(docker ps -aq)
		fi
		if docker ps -a
		then
		docker rm $(docker ps -aq)
		fi
		docker run -d --volume /log:/app homework:speedtest
                '''
            }
        }
    }
}
