FROM alpine:latest
RUN apk update && apk add --no-cache bash curl git wget
RUN mkdir /app
RUN curl -Lo speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
RUN chmod +x speedtest-cli
WORKDIR /app
COPY entrypoint_Shashkou.sh /entrypoint_Shashkou.sh
ENTRYPOINT ["/entrypoint_Shashkou.sh"]
