pipeline {
    agent {
        docker { 
            image 'alpine'
        }
    }

    parameters {
        gitParameter branchFilter: 'origin/(.*)', defaultValue: 'master', name: 'BRANCH', type: 'PT_BRANCH'
    }

    stages {
        stage("Verify deploy confirmation") {
            steps {
                timeout(time: 60, unit: 'SECONDS') {
                    input "Вы уверены?"
                }
            }

        }
        stage("Initial config") {
            steps {
                script {
                    properties([pipelineTriggers([pollSCM('* * * * *')])])
                }
            }
        }
        stage("Checkout Git") {
            steps {
                git branch: "${params.BRANCH}", url: 'https://github.com/valerypiotuh/belhard-devops.git' 
            }
        }
        stage("List repository") {
            steps {
                sh '''
                ls -la
                '''
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}
