version: '2.2'          # Версия формата файла docker-compose.yml
services:
  compose-nginx1:          # Имя сервиса
    build: ~/nginx/1    # Путь к Dockerfile. '.' означает текущую директорию, в которой лежит docker-compose.yml
    ports:          # Проброс портов
      - "8101:80"

  compose-nginx2:
    build: ~/nginx/2
    ports:          # Проброс портов
      - "8201:80"
