ansible-playbook -i hosts step1.yml
ansible-playbook -i hosts step2.yml
ansible-playbook -i hosts step3.yml
ansible-playbook -i hosts step4.yml
ansible-playbook -i hosts docker/step5.yml
ansible-playbook -i hosts docker/step6.yml
ansible-playbook -i hosts docker/step7.yml
ansible-playbook -i hosts docker/step8.yml
ansible-playbook -i hosts docker/step9.yml
ansible-playbook -i hosts postgres/step10.yml
ansible-playbook -i hosts postgres/step11.yml
ansible-playbook -i hosts postgres/step12.yml
